// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);

		int greaterCount = 0;
		int lessOrEqualCount = 0;

		for (int i=0; i<N; i++) {
			double x = Math.random();

			if (x > 0.5) {
				greaterCount = greaterCount + 1;
			} else {
				lessOrEqualCount = lessOrEqualCount + 1;
			}
		}

		System.out.print("> 0.5: " + greaterCount + " times ");
		System.out.print("<= 0.5 " + lessOrEqualCount + " times ");
		
		if (lessOrEqualCount > 0) {
			double ratio = (double) greaterCount / lessOrEqualCount;
			System.out.print("Ratio: " + ratio);
		}
	}
}
